/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#3525cd',
        'primary-container':         '#4f46e5',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#dad7ff',
        'primary-fixed':             '#e2dfff',
        'primary-fixed-dim':         '#c3c0ff',
        'on-primary-fixed':          '#0f0069',
        'on-primary-fixed-variant':  '#3323cc',
        'secondary':                 '#505f76',
        'secondary-container':       '#d0e1fb',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#54647a',
        'secondary-fixed':           '#d3e4fe',
        'secondary-fixed-dim':       '#b7c8e1',
        'on-secondary-fixed':        '#0b1c30',
        'on-secondary-fixed-variant':'#38485d',
        'tertiary':                  '#005338',
        'tertiary-container':        '#006e4b',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#67f4b7',
        'tertiary-fixed':            '#6ffbbe',
        'tertiary-fixed-dim':        '#4edea3',
        'on-tertiary-fixed':         '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'surface':                   '#f7f9fb',
        'surface-dim':               '#d8dadc',
        'surface-bright':            '#f7f9fb',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f2f4f6',
        'surface-container':         '#eceef0',
        'surface-container-high':    '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant':           '#e0e3e5',
        'surface-tint':              '#4d44e3',
        'on-surface':                '#191c1e',
        'on-surface-variant':        '#464555',
        'outline':                   '#777587',
        'outline-variant':           '#c7c4d8',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f3',
        'inverse-primary':           '#c3c0ff',
        'background':                '#f7f9fb',
        'on-background':             '#191c1e',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      /* Optional token for table headers / micro labels (use text-2xs) */
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'ambient': '0 10px 30px -10px rgba(25, 28, 30, 0.08)',
        'drawer': '0 0 40px -10px rgba(25, 28, 30, 0.15)',
      }
    },
  },
  plugins: [],
};
