/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Warm clay / terracotta — pairs with sand surfaces (no cool blue primary) */
        'primary':                   '#8f4334',
        'primary-container':         '#72362a',
        'on-primary':                '#fffdfb',
        'on-primary-container':      '#f4e6e2',
        'primary-fixed':             '#efe3df',
        'primary-fixed-dim':         '#d9c9c2',
        'on-primary-fixed':          '#3b221c',
        'on-primary-fixed-variant':  '#5a362c',
        'secondary':                 '#5c564e',
        'secondary-container':       '#e2dfd8',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#4a4640',
        'secondary-fixed':           '#e8e4de',
        'secondary-fixed-dim':       '#d5cfc6',
        'on-secondary-fixed':        '#2c2824',
        'on-secondary-fixed-variant':'#4a4540',
        'tertiary':                  '#005338',
        'tertiary-container':        '#006e4b',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#67f4b7',
        'tertiary-fixed':            '#6ffbbe',
        'tertiary-fixed-dim':        '#4edea3',
        'on-tertiary-fixed':         '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        /* Warm milky neutrals — soft paper, not stark white */
        'surface':                   '#e8e4dc',
        'surface-dim':               '#d2cdc4',
        'surface-bright':            '#f0ece5',
        'surface-container-lowest':  '#f6f2eb',
        'surface-container-low':     '#ebe7e0',
        'surface-container':         '#e3dfd8',
        'surface-container-high':    '#dbd7d0',
        'surface-container-highest': '#d3cfc8',
        'surface-variant':           '#dad6cf',
        'surface-tint':              '#8f4334',
        'on-surface':                '#2a2622',
        'on-surface-variant':        '#5e5852',
        'outline':                   '#8a8178',
        'outline-variant':           '#c9c0b5',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f3',
        'inverse-primary':           '#e8c4b8',
        'background':                '#e8e4dc',
        'on-background':             '#2a2622',
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      /* Optional token for table headers / micro labels (use text-2xs) */
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'ambient': '0 10px 30px -10px rgba(25, 28, 30, 0.08)',
        'drawer': '0 0 40px -10px rgba(25, 28, 30, 0.15)',
      }
    },
  },
  plugins: [],
};
